### PR TITLE
Don't open anchor links in new tabs

### LINKED ISSUE #1476: no link between slides
**Description**

When presenting slides, the feature to create links between slides does not work.

**To Reproduce**

1. Go to demo slides (of the demo instance)
2. Go to [page 18](https://demo.hedgedoc.org/p/slide-example#/17)
3. Click on link "like this"
4. See that the browser is redirected to home page

**Expected behavior**

The link should lead to slide `1/3`.

**Logs**

n/a

**Config**

n/a

**Setup:**

 - demo instance

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
Slide example

### Description
This PR make anchor links base uri independent by adding the window location to the link URL.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Fixes #1476

### CODE REVIEW

**Review by ErikMichelson — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

File: public/js/extra.js [hunk 1]
```diff
@@ -575,6 +575,14 @@ export function postProcess (code) {
   // also add noopener to prevent clickjacking
   // See details: https://mathiasbynens.github.io/rel-noopener/
   result.find('a:not([href^="#"]):not([target])').attr('target', '_blank').attr('rel', 'noopener')
+
+  // If it's hashtag link then make it base uri independent
+  result.find('a[href^="#"]').each((index, linkTag) => {
+    const currentLocation = new URL(window.location)
```
Comment (ErikMichelson) [inline public/js/extra.js:581]: I don't think we need to create this constant for every link?

**Review by ErikMichelson — APPROVED** [review]
