### PR TITLE
Convert history attribute in user table to long text

### LINKED ISSUE #2623: large history leads to error 500 from api due to cut off json in database
### Description

`/history` api throws error 500 due to cut off json in database

### Steps to reproduce

1. you need to have a large history, e.g. I have currently about 35 pages history in hedgedoc
2. open the front page of hedgedoc
3. `/history` throws an error 500, no history is shown
4. if `/history` does not throw an error 500, you need to open more notes

### Expected behaviour

`/history` api returns history data with status code 200

### Logs

```
2022-09-01T07:11:33.131Z info: 	deserializeUser: 563c5c12-XXXX-XXXX-XXXX-4b08ac8b11ec
2022-09-01T07:11:33.134Z error: 	read history failed: SyntaxError: Unexpected end of JSON input
2022-09-01T07:11:33.137Z info: 	10.75.4.2 - - [01/Sep/2022:07:11:33 +0000] "GET /history HTTP/1.1" 500 - "https://notes.XXXX.de/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
```

### Config

```
version: '2'
services:
  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.3
    environment:
      - "CMD_DOMAIN=notes.XXXXXX.de"
      - "CMD_URL_ADDPORT=false"
      - "CMD_PROTOCOL_USESSL=true"
      - "CMD_DB_URL=mysql://XXXXX:XXXXXXXXXXX@mysql.XXX.XXXX.de:3306/hackmd"
      - "CMD_DEFAULT_PERMISSION=editable"
      - "CMD_EMAIL=false"
      - "CMD_IMAGE_UPLOAD_TYPE=filesystem"
      - "CMD_SESSION_SECRET=XXXXXXX"
    volumes:
      - uploads:/hedgedoc/public/uploads
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notes.rule=Host(`notes.XXXX.XXXXX.de`)"
      - "traefik.http.services.notes.loadbalancer.server.port=3000"
volumes:
  uploads:
```

### Your Setup

- Host OS: Debian 10 with Docker Container `quay.io/hedgedoc/hedgedoc:1.9.3`
- NodeJS version: v16.16.0
- HedgeDoc version: 1.9.3

### Additional context

In the mysql database, the `Users`.`history` column is of type text, which limits it to 65,535 chars. When reaching this number of chars, the text is cut off, which results in invalid json and therefore the problem here. My quick fix was to use `longtext` instead of `text` and repairing the json syntax manually.

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
Database scheme

### Description
This PR changes the data type of the history attribute in the user table to long text.

When using mysql the normal text attribute has a fixed size. When this size is reached then the json will be cut off and becomes invalid. The problem doesn't occur when using postgres or sqlite because they already have variable length.

### Steps

- [x] Added implementation
- [x] Added changelog snippet
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
Fixes #2623

### CODE REVIEW

**Review by ErikMichelson — APPROVED** [review]

**Review by InnayTool — APPROVED** [review]

**Review by DerMolly — APPROVED** [review]

File: lib/migrations/20220901102800-convert-history-to-longtext.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+'use strict'
+
+module.exports = {
+  up: function (queryInterface, Sequelize) {
```
Comment (davidmehren) [inline lib/migrations/20220901102800-convert-history-to-longtext.js:4]: Please add a `down` method too.

**Review by davidmehren — CHANGES_REQUESTED** [review]

File: public/docs/release-notes.md [hunk 2]
```diff
@@ -7,6 +7,7 @@
 
 ### Bugfixes
 - Fix a crash when using LDAP authentication with custom search attributes (thanks to [@aboettger-tuhh](https://github.com/aboettger-tuhh) for reporting)
+- Change data type of history attribute in user table to long text to prevent truncated json when using mysql
```
Comment (davidmehren) [inline public/docs/release-notes.md:10]:
```suggestion
- Fix crash caused by a long note history when the MySQL database is used
```

**Review by davidmehren — APPROVED** [review]
