### PR TITLE
ImageUpload: Fix errors with .jpeg and .svg 

### LINKED ISSUE #744: Image upload error: Provided file extension does not match MIME-type
**Description**
I updated from codimd to hedgedoc today. I'm using minio as a backend for picture upload. Trying to upload images results in the following error. **The same config works with my old codimd setup**

```
error:         Image upload error: Provided file extension does not match MIME-type
```

**To Reproduce**
1. Install latest hedgedoc
2. Setup minio as pic-upload backend
3. Upload image (a regular old jpeg) to note

**Expected behavior**
I expect the upload to succeed.

**Config**

I'm using the following config snippet
```
"minio": {
    "accessKey": "codimd",
    "secretKey": "********",
    "endPoint": "*********",
    "secure": true,
    "port": 443
},
"s3bucket": "codimd",
"imageUploadType": "minio"
```

**Your Setup (please complete the following information):**
 - Host OS: CentOS 7
 - NodeJS version: v10.23.0
 - HedgeDoc version: 1.7.2

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
Image upload

### Description
This PR checks all files that claim to be an svg (by their extension) that they really are and defines the typeFromMagic accordingly
Files that got identified as jpg, but have the extension .jpeg get their extension fixed.
The files extensions will work in all cases now.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/hedgedoc/blob/develop/CONTRIBUTING.md) and
  made sure that:
  - My commits are signed-off to accept the DCO.
  - This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x

### Related Issue(s)
fixes #744

### CODE REVIEW

**Comment by DerMolly** [comment]
I tested with the whole suite of extensions:
[test-images.zip](https://github.com/hedgedoc/hedgedoc/files/6218030/test-images.zip)

**Review by InnayTool — DISMISSED** [review]

File: lib/web/imageRouter/index.js [hunk 1]
```diff
@@ -15,12 +16,25 @@ const errors = require('../../errors')
...
     return false
   }
-  if (path.extname(filePath) !== '.' + typeFromMagic.ext) {
+  if (extension === '.jpeg' && typeFromMagic.ext === 'jpg') {
+    typeFromMagic.ext = 'jpeg'
+  }
+  if (extension !== '.' + typeFromMagic.ext) {
     logger.error(
       'Image upload error: Provided file extension does not match MIME-type'
     )
```
Comment (ErikMichelson) [inline lib/web/imageRouter/index.js:40]: Why do we check the extension of the uploaded file at all if we already check the magic number and could use the extension provided by file-info for storing the file instead?

File: lib/web/imageRouter/index.js [hunk 2]
```diff
@@ -15,12 +16,25 @@ const errors = require('../../errors')
...
+    }
+  }
   if (typeFromMagic === undefined) {
     logger.error('Image upload error: Could not determine MIME-type')
     return false
   }
-  if (path.extname(filePath) !== '.' + typeFromMagic.ext) {
+  if (extension === '.jpeg' && typeFromMagic.ext === 'jpg') {
+    typeFromMagic.ext = 'jpeg'
+  }
```
Comment (ErikMichelson) [inline lib/web/imageRouter/index.js:36]: There do exist even more "jpeg" file extensions like .jpe or .jfif. [[1]]

If we drop the check (see my previous comment) this would become unnecessary.

[1]: https://de.wikipedia.org/wiki/JPEG_File_Interchange_Format

File: lib/web/imageRouter/index.js [hunk 3]
```diff
@@ -15,12 +16,25 @@ const errors = require('../../errors')
 const imageRouter = (module.exports = Router())
 
 async function checkUploadType (filePath) {
-  const typeFromMagic = await FileType.fromFile(filePath)
+  const extension = path.extname(filePath).toLowerCase()
+  let typeFromMagic = await FileType.fromFile(filePath)
+  if (extension === '.svg') {
```
Comment (ErikMichelson) [inline lib/web/imageRouter/index.js:21]: Instead of the comparison of the uploaded extension, you could check whether file-info reported the file as xml and then do the is-svg check.

File: lib/config/index.js [hunk 4]
```diff
@@ -179,15 +179,13 @@ switch (config.imageUploadType) {
...
       'image/gif'
     ]
     break
   default:
     config.allowedUploadMimeTypes = [
       'image/jpeg',
       'image/png',
-      'image/jpg',
       'image/gif',
       'image/svg+xml'
```
Comment (ErikMichelson) [inline lib/config/index.js:190]: Maybe we want to add the WebP image format as well? It's becoming more popular nowadays since Google's lighthouse recommends the usage of WebP format for web content.[[1]]

[1]: https://web.dev/uses-webp-images/

**Review by ErikMichelson — CHANGES_REQUESTED** [review]

File: lib/config/index.js (hunk 4 above)
Comment (DerMolly) [reply lib/config/index.js:190]: I would not add anything new anymore as this is just a bug fix.

File: lib/web/imageRouter/index.js (hunk 3 above)
Comment (DerMolly) [reply lib/web/imageRouter/index.js:21]: We tried that and not all svgs are found as xml (only those that start with ´<xml>` do), but there are qute a few svgs that just start with `<svg>`. Those aren't identified by FileType at all. `typeFromMagic` is just `undefined`.

File: lib/web/imageRouter/index.js (hunk 1 above)
Comment (DerMolly) [reply lib/web/imageRouter/index.js:40]: This fix was programmed in a way that does not rebuild the upload logic (and most likely introduce new bugs)…

File: lib/web/imageRouter/index.js (hunk 2 above)
Comment (DerMolly) [reply lib/web/imageRouter/index.js:36]: I'm not to sure that those formats are widely used, but I can add checks for those, too.

Comment (DerMolly) [reply lib/web/imageRouter/index.js]: Here are my test files.

Curiously `convert acid.svg acid.jfif` did not produce a correct `.jfif` file but some sort of svg…

[jpeg.zip](https://github.com/hedgedoc/hedgedoc/files/6222256/jpeg.zip)

File: lib/web/imageRouter/index.js (hunk 3 above)
Comment (ErikMichelson) [reply lib/web/imageRouter/index.js:21]: Ah okay, then nevermind.

**Review by InnayTool — DISMISSED** [review]

File: lib/web/imageRouter/index.js (hunk 2 above)
Comment (ErikMichelson) [reply lib/web/imageRouter/index.js]: okay

File: lib/config/index.js (hunk 4 above)
Comment (ErikMichelson) [reply lib/config/index.js:190]: okay

**Review by InnayTool — DISMISSED** [review]

**Review by InnayTool — APPROVED** [review]

**Review by davidmehren — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]
